---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ucore-server 
# description will be included in the image's metadata
description: Custom uCore Server

# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/ucore
base-image: quay.io/fedora/fedora-coreos 
image-version: stable # latest is also supported if you want new updates ASAP

modules:
  - type: dnf
    install:
      packages:
        - vim
        - btop
        - zsh
        - atuin
        - podlet
        - util-linux-script
        - rpmconf
## The following is here until ublue gets their images fixed
        - cockpit
        - cockpit-bridge
        - cockpit-storaged
        - cockpit-podman
        - cockpit-networkmanager
        - cockpit-selinux
        - cockpit-system
    remove:
      packages:
        - nano
  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - starship
  - type: signing

