# description will be included in the image's metadata
name: uBlue-uCore-test
description: Custom FCOS Server

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore 
image-version: stable-nvidia # latest is also supported if you want new updates ASAP

modules:
  - type: dnf
    install:
      packages:
        - vim
        - zsh
        - util-linux-script
        - rpmconf
    remove:
      packages:
        - nano
  - type: signing

