# description will be included in the image's metadata
name: Custom uBlue uCore Server
description: Custom FCOS Server

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore
image-version: stable # latest is also supported if you want new updates ASAP

modules:
  - type: dnf
    install:
      packages:
        - vim
        - zsh
        - util-linux-script
        - rpmconf
    remove:
      packages:
        - nano
  - type: brew
  - type: signing

